// services/mailer.js — emails the full meeting report to attendees

const nodemailer = require("nodemailer");

// Configure using Gmail — add these to your .env file:
// MAIL_USER=you@gmail.com
// MAIL_PASS=your_gmail_app_password  (not your real password)
// MAIL_TO=team@yourcompany.com       (comma separated recipients)
// Get app password at: myaccount.google.com/apppasswords

function createTransporter() {
  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.MAIL_USER,
      pass: process.env.MAIL_PASS,
    },
  });
}

function buildReportHTML(report, jiraResults) {
  const decisions = (report.keyDecisions || [])
    .map(d => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #eee">
          <strong>${d.decision}</strong><br>
          <span style="color:#666;font-size:13px">${d.rationale || ""}</span>
        </td>
        <td style="padding:8px;border-bottom:1px solid #eee;color:#666">
          ${d.owner || "—"}
        </td>
      </tr>`).join("");

  const tasks = (report.actionItems || [])
    .map(t => {
      const jira = jiraResults
        ? jiraResults.find(r => r.task === t.title && r.success)
        : null;

      const priorityColor = {
        high: "#ff4444", medium: "#ff9900", low: "#00aa44"
      }[t.priority] || "#999";

      return `
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">
            <strong>${t.title}</strong><br>
            <span style="color:#666;font-size:13px">${t.description || ""}</span>
            ${jira ? `<br><a href="${jira.url}" style="color:#0052cc;font-size:12px">🔵 ${jira.key}</a>` : ""}
          </td>
          <td style="padding:8px;border-bottom:1px solid #eee;color:#666">
            ${t.assignee || "—"}
          </td>
          <td style="padding:8px;border-bottom:1px solid #eee">
            <span style="color:${priorityColor};font-weight:600;font-size:12px">
              ${(t.priority || "medium").toUpperCase()}
            </span>
          </td>
          <td style="padding:8px;border-bottom:1px solid #eee;color:#666;font-size:12px">
            ${t.deadline || "—"}
          </td>
        </tr>`;
    }).join("");

  const openQs = (report.openQuestions || [])
    .map(q => `<li style="margin:4px 0;color:#555">${q}</li>`).join("");

  return `
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;color:#333">

      <div style="background:#1a1a2e;padding:20px;border-radius:8px;margin-bottom:24px">
        <h1 style="color:#fff;margin:0;font-size:20px">🤖 AI Meeting Report</h1>
        <p style="color:#aaa;margin:6px 0 0 0;font-size:13px">
          ${report.meetingTitle || "Meeting"} · ${report.estimatedDuration || ""}
        </p>
      </div>

      <div style="background:#f8f9fa;padding:16px;border-radius:8px;margin-bottom:20px">
        <h2 style="margin:0 0 8px 0;font-size:15px;color:#333">📋 Summary</h2>
        <p style="margin:0;line-height:1.6;color:#555">
          ${report.executiveSummary || "No summary available."}
        </p>
      </div>

      ${decisions ? `
      <h2 style="font-size:15px;color:#333">✅ Key Decisions</h2>
      <table width="100%" cellpadding="0" cellspacing="0"
             style="border-collapse:collapse;margin-bottom:20px">
        <tr style="background:#f0f0f0">
          <th style="padding:8px;text-align:left;font-size:13px">Decision</th>
          <th style="padding:8px;text-align:left;font-size:13px;width:120px">Owner</th>
        </tr>
        ${decisions}
      </table>` : ""}

      ${tasks ? `
      <h2 style="font-size:15px;color:#333">🎯 Action Items</h2>
      <table width="100%" cellpadding="0" cellspacing="0"
             style="border-collapse:collapse;margin-bottom:20px">
        <tr style="background:#f0f0f0">
          <th style="padding:8px;text-align:left;font-size:13px">Task</th>
          <th style="padding:8px;text-align:left;font-size:13px;width:100px">Assignee</th>
          <th style="padding:8px;text-align:left;font-size:13px;width:80px">Priority</th>
          <th style="padding:8px;text-align:left;font-size:13px;width:100px">Deadline</th>
        </tr>
        ${tasks}
      </table>` : ""}

      ${openQs ? `
      <h2 style="font-size:15px;color:#333">❓ Open Questions</h2>
      <ul style="margin:0 0 20px 0;padding-left:20px">${openQs}</ul>` : ""}

      <div style="border-top:1px solid #eee;padding-top:12px;
                  color:#aaa;font-size:11px;text-align:center">
        Generated by AI Meeting Agent · ${new Date().toLocaleString()}
      </div>

    </body>
    </html>
  `;
}

async function emailReport(report, jiraResults) {
  const mailUser = process.env.MAIL_USER;
  const mailTo   = process.env.MAIL_TO;

  if (!mailUser || !mailTo) {
    console.log("[mailer] Skipping email — MAIL_USER or MAIL_TO not set in .env");
    return { skipped: true };
  }

  const transporter = createTransporter();
  const html = buildReportHTML(report, jiraResults);

  const attendees = (report.attendees || []).join(", ") || "the team";
  const subject = `[Meeting Report] ${report.meetingTitle || "Meeting"} — ${new Date().toLocaleDateString()}`;

  await transporter.sendMail({
    from:    `"AI Meeting Agent" <${mailUser}>`,
    to:      mailTo,
    subject,
    html,
    // Plain text fallback
    text: `
Meeting Report: ${report.meetingTitle || "Meeting"}
Duration: ${report.estimatedDuration || ""}

SUMMARY:
${report.executiveSummary || ""}

ACTION ITEMS:
${(report.actionItems || []).map(t =>
  `- ${t.title} → ${t.assignee || "Unassigned"} (${t.priority})`
).join("\n")}

DECISIONS:
${(report.keyDecisions || []).map(d => `- ${d.decision}`).join("\n")}

OPEN QUESTIONS:
${(report.openQuestions || []).map(q => `- ${q}`).join("\n")}
    `.trim(),
  });

  console.log(`[mailer] Report emailed to ${mailTo}`);
  return { sent: true, to: mailTo };
}

module.exports = { emailReport };